spring:
  application:
    name: consumer
  #MQTT配置信息
  mqtt:
    #MQTT服务端地址，端口默认为11883，如果有多个，用逗号隔开
    url: tcp://broker.emqx.io:1883
    #用户名
    username: emqx1111
    #密码
    password: public111
    #客户端id（不能重复）
    client:
      id: consumer-id
    #MQTT默认的消息推送主题，实际可在调用接口时指定
    default:
      topic: topic132
server:
  port: 8085
